import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretandardSans = localFont({
  src: "/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretandardSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
